apiVersion: v1
kind: ConfigMap
metadata:
  name: app-config
data:
  runtime-config.js: |
    window['runConfig'] = {
      apiBaseUrl: '{{ .Values.app.uris.api }}',
      socketUrl: '{{ .Values.app.uris.socket }}'
    }