apiVersion: v1
kind: Service
metadata:
  name: app-svc
  labels:
    app: krateo.io
    component: api
spec:
  selector:
    component: app
  type: ClusterIP
  ports:
    - name: http
      port: 80
      targetPort: 8080